package Reto5;


import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Yeida
 */
public class InterfaceUsuario extends javax.swing.JFrame {

    ArrayList<CuerpoDeAgua> cuerpas = new ArrayList<>();
    ArrayList<DensidadPoblacional> densidad = new ArrayList<>();
    String mostrame = "";
    String mostramelo = "";
    String mostrar = "";
    String mostrarlo = "";

    /**
     * Creates new form InterfaceUsuario
     */
    public InterfaceUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDensidadCant = new javax.swing.JTextField();
        txtDensidadMunicipio = new javax.swing.JTextField();
        txtDensidadID = new javax.swing.JTextField();
        btnDensidadIngresar = new javax.swing.JButton();
        btnDensidadVerAfeccion = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDensidadIngresar = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDensidadVerAfeccion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCuerpoNombre = new javax.swing.JTextField();
        txtCuerpoMunicipio = new javax.swing.JTextField();
        txtCuerpoTipoAgua = new javax.swing.JTextField();
        txtCuerpoIRCA = new javax.swing.JTextField();
        txtCuerpoID = new javax.swing.JTextField();
        txtCuerpoTipoCuerpo = new javax.swing.JTextField();
        btnCuerpoIngresar = new javax.swing.JButton();
        btnCuerpoProcesar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCuerpoSalidas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCuerpoIngresados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Cantidad de Habitantes");

        jLabel8.setText("Municipio");

        jLabel9.setText("ID");

        btnDensidadIngresar.setText("Ingresar");
        btnDensidadIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDensidadIngresarActionPerformed(evt);
            }
        });

        btnDensidadVerAfeccion.setText("Ver Afección");
        btnDensidadVerAfeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDensidadVerAfeccionActionPerformed(evt);
            }
        });

        txtDensidadIngresar.setColumns(20);
        txtDensidadIngresar.setRows(5);
        jScrollPane3.setViewportView(txtDensidadIngresar);

        txtDensidadVerAfeccion.setColumns(20);
        txtDensidadVerAfeccion.setRows(5);
        jScrollPane4.setViewportView(txtDensidadVerAfeccion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDensidadIngresar)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDensidadCant)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtDensidadMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtDensidadID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btnDensidadVerAfeccion))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDensidadCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDensidadMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDensidadID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDensidadIngresar)
                    .addComponent(btnDensidadVerAfeccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("DensidadPoblacional", jPanel2);

        jLabel1.setText("Nombre");

        jLabel2.setText("IRCA");

        jLabel3.setText("Tipo De Cuerpo");

        jLabel4.setText("Tipo De Agua");

        jLabel6.setText("ID");

        jLabel7.setText("Municipio");

        btnCuerpoIngresar.setText("Ingresar");
        btnCuerpoIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuerpoIngresarActionPerformed(evt);
            }
        });

        btnCuerpoProcesar.setText("Procesar");
        btnCuerpoProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuerpoProcesarActionPerformed(evt);
            }
        });

        txtCuerpoSalidas.setColumns(20);
        txtCuerpoSalidas.setRows(5);
        jScrollPane1.setViewportView(txtCuerpoSalidas);

        txtCuerpoIngresados.setColumns(20);
        txtCuerpoIngresados.setRows(5);
        jScrollPane2.setViewportView(txtCuerpoIngresados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(txtCuerpoIRCA, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(txtCuerpoNombre))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel7)
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCuerpoID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(txtCuerpoMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCuerpoTipoAgua, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txtCuerpoTipoCuerpo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCuerpoIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCuerpoProcesar)
                        .addGap(205, 205, 205))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuerpoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuerpoMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuerpoTipoAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuerpoIRCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuerpoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuerpoTipoCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCuerpoIngresar)
                    .addComponent(btnCuerpoProcesar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("CuerpoDeAgua", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuerpoIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuerpoIngresarActionPerformed
        // TODO add your handling code here:
        String nombre = txtCuerpoNombre.getText();
        byte ID = Byte.parseByte(txtCuerpoID.getText());
        String municipio = txtCuerpoMunicipio.getText();
        String tipoCuerpo = txtCuerpoTipoCuerpo.getText();
        String tipoAgua = txtCuerpoTipoAgua.getText();
        Float IRCA = Float.parseFloat(txtCuerpoIRCA.getText());

        cuerpas.add(new CuerpoDeAgua(nombre, ID, municipio, tipoCuerpo, tipoAgua, IRCA));
        mostrame += nombre + " " + ID + " " + municipio + " " + tipoCuerpo + " " + tipoAgua + " " + IRCA + "\n";
        txtCuerpoIngresados.setText(mostrame);
        JOptionPane.showMessageDialog(rootPane, "Regisrado Correctamente");

        txtCuerpoNombre.setText("");
        txtCuerpoID.setText("");
        txtCuerpoMunicipio.setText("");
        txtCuerpoTipoCuerpo.setText("");
        txtCuerpoTipoAgua.setText("");
        txtCuerpoIRCA.setText("");
        mostrar = "";
    }//GEN-LAST:event_btnCuerpoIngresarActionPerformed

    private void btnCuerpoProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuerpoProcesarActionPerformed
        // TODO add your handling code here:
        CuerpoDeAgua menor = cuerpas.get(0);
        String nombres = "";
        byte medioInferior = 0;
        for (CuerpoDeAgua cuerpo : cuerpas) {
            mostrar += cuerpo.nivel() + "\n";
        }

        for (CuerpoDeAgua cuerpo : cuerpas) {
            if (menor.getIRCA() > cuerpo.getIRCA()) {
                menor = cuerpo;
            }
            if (cuerpo.getIRCA() <= 35) {
                medioInferior++;
            }
        }

        mostrar += medioInferior + ",00" + "\n";
        for (CuerpoDeAgua cuerpo : cuerpas) {
            if ("MEDIO".equals(cuerpo.nivel())) {
                mostrar += cuerpo.getNombre() + "\n";
            }
        }
        mostrar += menor.getNombre() + " " + menor.getID() + ",00";
        txtCuerpoSalidas.setText(mostrar);
    }//GEN-LAST:event_btnCuerpoProcesarActionPerformed

    private void btnDensidadIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDensidadIngresarActionPerformed
        // TODO add your handling code here:
        int cantHabitantes = Integer.parseInt(txtDensidadCant.getText());
        byte ID = Byte.parseByte(txtDensidadID.getText());
        String municipio = txtDensidadMunicipio.getText();
        densidad.add(new DensidadPoblacional(cantHabitantes, ID, municipio));

        mostramelo += municipio + " tiene " + cantHabitantes + " habitantes" + "\n";
        txtDensidadIngresar.setText(mostramelo);
        JOptionPane.showMessageDialog(rootPane, "Regisrado Correctamente");

        txtDensidadMunicipio.setText("");
        txtDensidadID.setText("");
        txtDensidadCant.setText("");
        mostrarlo = "";
    }//GEN-LAST:event_btnDensidadIngresarActionPerformed

    private void btnDensidadVerAfeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDensidadVerAfeccionActionPerformed
        // TODO add your handling code here:
        for (DensidadPoblacional densi : densidad) {
            mostrarlo += densi.getMunicipio() + " tiene un nivel de afectación " + densi.afeccion() + "\n";
        }
        txtDensidadVerAfeccion.setText(mostrarlo);
    }//GEN-LAST:event_btnDensidadVerAfeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuerpoIngresar;
    private javax.swing.JButton btnCuerpoProcesar;
    private javax.swing.JButton btnDensidadIngresar;
    private javax.swing.JButton btnDensidadVerAfeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtCuerpoID;
    private javax.swing.JTextField txtCuerpoIRCA;
    private javax.swing.JTextArea txtCuerpoIngresados;
    private javax.swing.JTextField txtCuerpoMunicipio;
    private javax.swing.JTextField txtCuerpoNombre;
    private javax.swing.JTextArea txtCuerpoSalidas;
    private javax.swing.JTextField txtCuerpoTipoAgua;
    private javax.swing.JTextField txtCuerpoTipoCuerpo;
    private javax.swing.JTextField txtDensidadCant;
    private javax.swing.JTextField txtDensidadID;
    private javax.swing.JTextArea txtDensidadIngresar;
    private javax.swing.JTextField txtDensidadMunicipio;
    private javax.swing.JTextArea txtDensidadVerAfeccion;
    // End of variables declaration//GEN-END:variables
}
